[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
goblin = { version = "0.5", default-features = false, features = ["archive", "std"] }
rustc_version = "0.4"
xflags = "0.2"
xshell = "0.2"
