name: aarch64

on:
  pull_request:
  push:
    branches:
      - master
      - staging
      - trying

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    shell: bash

jobs:
  test:
    name: aarch64 tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout rusty-hermit
        uses: actions/checkout@v3
        with:
          repository: hermitcore/rusty-hermit
          submodules: true
          ref: 04ca4407fd6823972a6950e3d59a157208be4f00
      - name: Remove libhermit-rs submodule
        run: git rm -r libhermit-rs
      - name: Checkout libhermit-rs
        uses: actions/checkout@v3
        with:
          path: libhermit-rs
      - name: Rustup (apply rust-toolchain.toml)
        working-directory: libhermit-rs
        run: rustup show
      - name: Build minimal kernel
        working-directory: libhermit-rs
        run: cargo xtask build --arch aarch64 --no-default-features
      - name: Build dev profile
        run: cargo build -Zbuild-std=core,alloc,std,panic_abort -Zbuild-std-features=compiler-builtins-mem --target aarch64-unknown-hermit --package hello_world
      - name: Build loader
        run: make arch=aarch64
        working-directory: loader
        env:
          HERMIT_APP: ../../../../target/aarch64-unknown-hermit/debug/hello_world
      - name: Install QEMU
        run: |
          sudo apt-get update
          sudo apt-get install qemu-system-aarch64
      - name: Test kernel
        run: qemu-system-aarch64 -semihosting -display none -serial stdio -kernel target/aarch64-unknown-hermit-loader/debug/rusty-loader -machine virt,gic-version=max -m 512M -cpu max -smp 1
        working-directory: loader
        
